# Generated by Django 2.2 on 2020-02-21 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BeltReviewApp', '0002_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user_review',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
