# Generated by Django 2.2 on 2020-02-21 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeltReviewApp', '0003_book_user_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='BeltReviewApp.User')),
                ('users_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='BeltReviewApp.Book')),
            ],
        ),
    ]
